/* eslint-disable no-unused-vars */
// slice is splitting the redux store into multiple parts
// ex: Orders slice, Products slice, etc.
// It will be easier to manage
// A slice will contain the initial state, reducers, and actions for a particular feature or domain of the application.
// A reducer is a function that takes the current state and an action, and returns a new state.
// A state is an object that contains the data for the application.

import { createSlice } from "@reduxjs/toolkit";
import { resetDestination } from "./destinationSlice";
import { resetReduxOPedia } from "../action/actions";

// This is an object, we can have multiple properties in this object
// Each property can be a different part of the state
const initialState = {
    count: 10,
};

export const counterSlice = createSlice({
    name: "counter", // Name of the slice, used for debugging and logging
    // The name should be unique across all slices in the store
    initialState, // initial value of the state for this slice
    // The initial state is the state that the slice will start with
    // Reducers are functions that take the current state and an action, and return a new state
    // Each reducer is a function that handles a specific action    
    // The reducer functions are used to update the state of the slice
    // It will have all actions that can be performed on the state of this slice
    reducers: {
        // state is the current state of the slice, not the reducx store
        // action is the action that is dispatched to the reducer
        // Each action is a function that takes the current state and returns a new state
        // The action can be dispatched to the reducer to update the state
        // With reducx toolkit, we can directly mutate the state in the reducer functions
        // This is because Redux Toolkit uses Immer under the hood, which allows us to write "mutating" code that is actually immutable
        // The action creators are automatically generated by Redux Toolkit
        // We don't have to spread the state or return a new state object manually
        increment: (state) => {
            state.count += 1; // Directly mutating the state is allowed in Redux Toolkit
        },
        decrement: (state) => {
            state.count -= 1;
        },
        reset: (state) => {
            state.count = 10;
        },
        decrementMultiplier: (state, action) => {
            // This action can be used to decrement the count by a multiplier
            // The action payload can be used to specify the multiplier
            const multiplier = Number(action.payload.multiplier); // Default to 1 if no payload is provided
            state.count -= multiplier;
        },
        incrementMultiplier: (state, action) => {
            // This action can be used to increment the count by a multiplier
            // The action payload can be used to specify the multiplier
            const multiplier = Number(action.payload.multiplier); // Default to 1 if no payload is provided
            state.count += multiplier;
        },
        resetMultiplier: (state) => {
            // This action can be used to reset the count to 0
            state.count = 10;
        },
    },
    extraReducers: (builder) => {
        // magic strings are bad and should be avoided
        builder.addCase(resetDestination.toString(), (state, action) => {
            state.count = 10;
        });
        builder.addCase(resetReduxOPedia.toString(), (state, action) => {
            state.count = 100;
        });
    }
});

export const { increment, decrement, reset, incrementMultiplier, decrementMultiplier, resetMultiplier } = counterSlice.actions;
// Exporting the actions so that they can be used in the components
export const counterReducer = counterSlice.reducer; // Exporting the reducer so that it can be used in the store